// Built from tag v3.1.0

using System;

namespace FINT.Model.Utdanning.Vurdering
{
	public enum VurderingActions
    {
	
	GET_EKSAMENSGRUPPE,
	GET_ALL_EKSAMENSGRUPPE,
	UPDATE_EKSAMENSGRUPPE,
	GET_FRAVAR,
	GET_ALL_FRAVAR,
	UPDATE_FRAVAR,
	GET_KARAKTERVERDI,
	GET_ALL_KARAKTERVERDI,
	UPDATE_KARAKTERVERDI,
	GET_VURDERING,
	GET_ALL_VURDERING,
	UPDATE_VURDERING
    }
}
