// Built from tag v3.5.0

using System;

namespace FINT.Model.Utdanning.Kodeverk
{
	public enum KodeverkActions
    {
	
	GET_ELEVKATEGORI,
	GET_ALL_ELEVKATEGORI,
	UPDATE_ELEVKATEGORI,
	GET_FRAVARSTYPE,
	GET_ALL_FRAVARSTYPE,
	UPDATE_FRAVARSTYPE,
	GET_KARAKTERSKALA,
	GET_ALL_KARAKTERSKALA,
	UPDATE_KARAKTERSKALA,
	GET_SKOLEAR,
	GET_ALL_SKOLEAR,
	UPDATE_SKOLEAR,
	GET_SKOLEEIERTYPE,
	GET_ALL_SKOLEEIERTYPE,
	UPDATE_SKOLEEIERTYPE,
	GET_TERMIN,
	GET_ALL_TERMIN,
	UPDATE_TERMIN
    }
}
