// Built from tag v2.6.0-rc-1

using System;

namespace FINT.Model.Utdanning.Kodeverk
{
	public enum KodeverkActions
    {
	
	GET_ELEVKATEGORI,
	GET_ALL_ELEVKATEGORI,
	UPDATE_ELEVKATEGORI,
	GET_FRAVARSTYPE,
	GET_ALL_FRAVARSTYPE,
	UPDATE_FRAVARSTYPE,
	GET_KARAKTERSKALA,
	GET_ALL_KARAKTERSKALA,
	UPDATE_KARAKTERSKALA,
	GET_SKOLEEIERTYPE,
	GET_ALL_SKOLEEIERTYPE,
	UPDATE_SKOLEEIERTYPE
    }
}
