// Built from tag v3.3.0-rc-1

using System;

namespace FINT.Model.Utdanning.Utdanningsprogram
{
	public enum UtdanningsprogramActions
    {
	
	GET_PROGRAMOMRADE,
	GET_ALL_PROGRAMOMRADE,
	UPDATE_PROGRAMOMRADE,
	GET_SKOLE,
	GET_ALL_SKOLE,
	UPDATE_SKOLE,
	GET_UTDANNINGSPROGRAM,
	GET_ALL_UTDANNINGSPROGRAM,
	UPDATE_UTDANNINGSPROGRAM,
	GET_ARSTRINN,
	GET_ALL_ARSTRINN,
	UPDATE_ARSTRINN
    }
}
