// Built from tag v3.5.0

using System;

namespace FINT.Model.Utdanning.Timeplan
{
	public enum TimeplanActions
    {
	
	GET_FAG,
	GET_ALL_FAG,
	UPDATE_FAG,
	GET_ROM,
	GET_ALL_ROM,
	UPDATE_ROM,
	GET_TIME,
	GET_ALL_TIME,
	UPDATE_TIME,
	GET_UNDERVISNINGSGRUPPE,
	GET_ALL_UNDERVISNINGSGRUPPE,
	UPDATE_UNDERVISNINGSGRUPPE,
	GET_UNDERVISNINGSGRUPPEMEDLEMSKAP,
	GET_ALL_UNDERVISNINGSGRUPPEMEDLEMSKAP,
	UPDATE_UNDERVISNINGSGRUPPEMEDLEMSKAP
    }
}
