// Built from tag v2.6.0-beta-1

using System;

namespace FINT.Model.Utdanning.Elev
{
	public enum ElevActions
    {
	
	GET_BASISGRUPPE,
	GET_ALL_BASISGRUPPE,
	UPDATE_BASISGRUPPE,
	GET_ELEV,
	GET_ALL_ELEV,
	UPDATE_ELEV,
	GET_ELEVFORHOLD,
	GET_ALL_ELEVFORHOLD,
	UPDATE_ELEVFORHOLD,
	GET_KONTAKTLARERGRUPPE,
	GET_ALL_KONTAKTLARERGRUPPE,
	UPDATE_KONTAKTLARERGRUPPE,
	GET_MEDLEMSKAP,
	GET_ALL_MEDLEMSKAP,
	UPDATE_MEDLEMSKAP,
	GET_UNDERVISNINGSFORHOLD,
	GET_ALL_UNDERVISNINGSFORHOLD,
	UPDATE_UNDERVISNINGSFORHOLD
    }
}
